services:
  - type: web
    name: accessible-navigation-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node backend/server.js"
    autoDeploy: true
